[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osr2-broker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pyserial",
    "PyQt6",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
testpaths = ["tests"]
